version: '3.5'
# 网络配置
networks:
  default:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:cached
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:cached
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

 
  php:
    build:
      context: ./services/php8
      args:
        PHP_VERSION: php:${PHP8_VERSION}-fpm-alpine3.15
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP8_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    volumes:
      - ${SOURCE_DIR}:/www/:cached
      - ${PHP8_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:cached
      - ${PHP8_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:cached
      - ${PHP8_LOG_DIR}:/var/log/php:cached
      - ${DATA_DIR}/composer:/tmp/composer
      - ${SUPERVISOR_LOG}:/var/log/supervisor/:rw
      - ${SUPERVISOR_CONFIG}:/etc/supervisor/conf.d/:rw
      - ${SUPERVISOR_CONF_FILE}:/etc/supervisor/supervisord.conf:ro
    restart: always
    cap_add:
      - SYS_PTRACE
    command:
      - /bin/sh
      - -c
      - |
        supervisord -n -c /etc/supervisor/supervisord.conf
    networks:
      - default


  php7:
    build:
      context: ./services/php7
      args:
        PHP_VERSION: php:${PHP7_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP7_EXTENSIONS}
        TZ: "$TZ"
    container_name: php7
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP7_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP7_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP7_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default


  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    command: --lower_case_table_names=1 
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
      

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default

  golang:                                # 自定义容器名称
    build:
      context: ./services/golang                  # 指定构建使用的 Dockerfile 文件
    container_name: golang
    environment:                         # 设置环境变量
      - TZ=${TZ}
    volumes:                             # 设置挂载目录
      - ${SOURCE_DIR}:/usr/src/code     # 引用 .env 配置中 SOURCE_DIR 变量，将宿主机上代码存放的目录挂载到容器中 /usr/src/code 目录
    ports:                               # 设置端口映射
      - "8000:8000"
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - default
    restart: always                      # 指定容器退出后的重启策略为始终重启

  remix:
    image: remixproject/remix-ide:remix_live
    container_name: remix
    ports:
      - "${REXIX_HOST_PORT}:80"
    restart: always
    networks:
      - default 
        
  portainer:
    image: ${PORTAINER_VERSION}
    container_name: portainer
    ports:
      - "${PORTAINER_HOST_PORT}:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:cached
      - ${PORTAINER_DATA_DIR}:/data:cached
    networks:
      - default 